package ru.urvanov.itdating;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

public class WomanNames {
    
    static final List<String> WOMAN_NAMES;

    static {
        List<String> tempWomanNames = List.of(
                "oksana",
                "оксана",
                "anna",
                "аня",
                "olya",
                 "olga",
                 "ольга",
                 "оля",
                 "jamilya",
                 "джамиля",
                 "anastasiya",
                 "anastasia",
                 "nastya",
                 "анастасия",
                 "настя",
                 "christina",
                 "кристина",
                 "yana",
                 "яна",
                 "marina",
                 "марина",
                 "irina",
                 "ирина",
                 "ira",
                 "ира",
                 "настенька",
                 "мариночка",
                 "евгения",
                 "evgeniya",
                 "evgenia",
                 "ekaterina",
                 "кaterina",
                 "катерина",
                 "екатерина",
                 "kate",
                 "катенька",
                 "nadia",
                 "nadeshda",
                 "nadezhda",
                 "nadya",
                 "надежда",
                 "надя",
                 "наденька",
                 "sveta",
                 "svetlana",
                 "света",
                 "светлана",
                 "анжелика",
                 "angelica",
                 "angelika",
                 "elizaveta",
                 "елизавета",
                 "liza",
                 "лиза",
                 "alla",
                 "алла",
                 "олеся",
                 "olesya",
                 "olesia",
                 "vika",
                 "vica",
                 "вика",
                 "виктория",
                 "victoria",
                 "victoriya",
                 "vasilisa",
                 "василиса",
                 "galya",
                 "galina",
                 "галя",
                 "галина",
                 "dana",
                 "дана",
                 "darya",
                 "daria",
                 "дарья",
                 "елена",
                 "elena",
                 "лена",
                 "lena",
                 "евдокия",
                 "evdokia",
                 "evdokiya",
                 "zoya",
                 "zoia",
                 "зоя",
                 "zina",
                 "зина",
                 "girl",
                 "девушк",
                 "девочк",
                 "karina",
                 "carina",
                 "карина",
                 "larisa",
                 "лариса",
                 "lyubov",
                 "любовь",
                 "margarita",
                 "маргарита",
                 "nina",
                 "нина",
                 "nataliya",
                 "наталья",
                 "natalia",
                 "sneshana",
                 "snejhana",
                 "snejana",
                 "снежана",
                 "полина",
                 "polina",
                 "sofia",
                 "sofiya",
                 "софия",
                 "tatyana",
                 "tanya",
                 "tatiana",
                 "tania",
                 "татьяна",
                 "таня",
                 "yulia",
                 "yulya",
                 "юля",
                 "ульяна",
                 "ulyana",
                 "uliana",
                 "faina",
                 "фаина",
                 "rada",
                 "рада"
                );
        tempWomanNames = new ArrayList<>(tempWomanNames);
        tempWomanNames.sort(Comparator.naturalOrder());
        WOMAN_NAMES = Collections.unmodifiableList(tempWomanNames);
    }
    
    private WomanNames() {}

}
